name: alzeh
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.0
  flutter_screenutil: ^5.9.3
  image_picker: ^1.2.0
  curved_navigation_bar: ^1.0.6

  # Firebase dependencies
  firebase_core: ^3.6.0
  firebase_database: ^11.1.4
  firebase_auth: ^5.3.1  # Optional for authentication


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  # Assets
  assets:
    - assets/icons/
    - assets/images/