// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUurPYe_p_VpM1zPje0c9U9tsYgmRV5bA',
    appId: '1:495317171778:android:ad3d4e685b27d1507af7db',
    messagingSenderId: '495317171778',
    projectId: 'medication-cc318',
    databaseURL: 'https://medication-cc318-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'medication-cc318.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjBYD3bqR9CnfLH-19suRYcN4zzWEndTQ',
    appId: '1:495317171778:ios:5eb15001285edfd57af7db',
    messagingSenderId: '495317171778',
    projectId: 'medication-cc318',
    databaseURL: 'https://medication-cc318-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'medication-cc318.firebasestorage.app',
    iosBundleId: 'com.example.alzeh',
  );
}
